### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by lcxsnow** [frejanordsiek/hdf5storage#103]
My equipments are python==3.6.9, hdf5storage==0.1.15, h5py==3.1.0
When I'm running "hdf5storage.savemat(test.mat, matcontent), it appears

Traceback (most recent call last):
File "prepare_data.py", line 98, in
hdf5storage.savemat(destinationfilenameclean, matcontent)
File "/home/snow/venv/lib/python3.6/site-packages/hdf5storage/init.py", line 1681, in savemat
options=options)
File "/home/snow/venv/lib/python3.6/site-packages/hdf5storage/init.py", line 1319, in writes
None, options)
File "/home/snow/venv/lib/python3.6/site-packages/hdf5storage/lowlevel.py", line 114, in write_data
m.write(f, grp, name, data, type_string, options)
File "/home/snow/venv/lib/python3.6/site-packages/hdf5storage/Marshallers.py", line 834, in write
**filters)
File "/home/snow/venv/lib/python3.6/site-packages/h5py/_hl/group.py", line 148, in create_dataset
dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
File "/home/snow/venv/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 137, in make_new_dset
dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "h5py/h5d.pyx", line 87, in h5py.h5d.create
ValueError: Unable to create dataset (no write intent on file)

What's the problem with this? Please help me fix it. THX

**Comment by frejanordsiek** [comment]
This issue is fixed in a more recent commit on the v0.1.x branch, but hasn't been released yet. I have to track down a fix the problem in #102 and will make a new release.

**Comment by frejanordsiek** [comment]
I will be uploading version 0.1.16 to PyPI shortly, which has this fix.
